<#
.SYNOPSIS
    Set up a keyboard shortcut for `picrypt panic` on Windows.

.DESCRIPTION
    Creates a desktop shortcut (.lnk) with a hotkey (Ctrl+Shift+L) that runs
    `picrypt panic`. Also creates a batch file wrapper if the picrypt binary
    is not directly accessible.

    Does NOT require Administrator. Safe to run multiple times (idempotent).

.PARAMETER Shortcut
    Keyboard shortcut to assign. Default: Ctrl+Shift+L.
    Note: Windows .lnk hotkeys only support Ctrl+Alt+<key> or Ctrl+Shift+<key>.

.PARAMETER PicryptPath
    Explicit path to the picrypt binary. Auto-detected if not provided.
#>

[CmdletBinding()]
param(
    [string]$PicryptPath = "",
    [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

function Write-LogInfo  { param([string]$Message) Write-Host "[INFO]  $Message" }
function Write-LogWarn  { param([string]$Message) Write-Host "[WARN]  $Message" -ForegroundColor Yellow }
function Write-LogError { param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }
function Write-LogOk    { param([string]$Message) Write-Host "[OK]    $Message" -ForegroundColor Green }

# --------------------------------------------------------------------------- #
# 1. Locate the picrypt binary
# --------------------------------------------------------------------------- #

Write-LogInfo "Locating picrypt binary..."

$picryptBin = $PicryptPath

if ([string]::IsNullOrEmpty($picryptBin)) {
    # Search common locations.
    $searchPaths = @(
        (Get-Command "picrypt" -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
        "$env:USERPROFILE\.cargo\bin\picrypt.exe",
        "$env:ProgramFiles\picrypt\picrypt.exe",
        "${env:ProgramFiles(x86)}\picrypt\picrypt.exe",
        "$env:LOCALAPPDATA\picrypt\picrypt.exe"
    )

    foreach ($candidate in $searchPaths) {
        if (-not [string]::IsNullOrEmpty($candidate) -and (Test-Path $candidate)) {
            $picryptBin = $candidate
            break
        }
    }
}

$picryptFound = $false
if (-not [string]::IsNullOrEmpty($picryptBin) -and (Test-Path $picryptBin)) {
    $picryptBin = (Resolve-Path $picryptBin).Path
    $picryptFound = $true
    Write-LogOk "Found picrypt at: $picryptBin"
} else {
    Write-LogWarn "picrypt binary not found."
    Write-LogWarn "A batch wrapper will be created that assumes 'picrypt' is in PATH."
    $picryptBin = "picrypt"
}

# --------------------------------------------------------------------------- #
# 2. Create a batch file wrapper
# --------------------------------------------------------------------------- #

# The batch wrapper ensures PATH is set correctly and provides a target for
# the .lnk shortcut (Windows shortcuts work best with .exe/.bat/.cmd targets).

$picryptDir = "$env:LOCALAPPDATA\picrypt"
$batchFile = "$picryptDir\picrypt-panic.bat"

Write-LogInfo "Creating batch wrapper at $batchFile..."

if (-not (Test-Path $picryptDir)) {
    New-Item -ItemType Directory -Path $picryptDir -Force | Out-Null
}

$batchContent = @"
@echo off
REM picrypt-panic.bat — Emergency lock all picrypt devices.
REM Generated by setup-hotkey-windows.ps1. Safe to regenerate.

setlocal

REM Add common binary locations to PATH.
set "PATH=%USERPROFILE%\.cargo\bin;%ProgramFiles%\picrypt;%LOCALAPPDATA%\picrypt;%PATH%"

echo [picrypt] Sending panic lock to all devices...
"@

if ($picryptFound) {
    $batchContent += "`n`"$picryptBin`" panic"
} else {
    $batchContent += "`npicrypt panic"
}

$batchContent += @"

if %ERRORLEVEL% NEQ 0 (
    echo [picrypt] PANIC LOCK FAILED with exit code %ERRORLEVEL%
    pause
    exit /b %ERRORLEVEL%
)

echo [picrypt] Panic lock sent successfully.
REM Brief pause so the user can see the result, then close.
timeout /t 2 /nobreak >nul
"@

Set-Content -Path $batchFile -Value $batchContent -Encoding ASCII
Write-LogOk "Batch wrapper created: $batchFile"

# --------------------------------------------------------------------------- #
# 3. Create desktop shortcut with hotkey
# --------------------------------------------------------------------------- #

$desktopPath = [Environment]::GetFolderPath("Desktop")
$shortcutPath = "$desktopPath\Picrypt Panic Lock.lnk"

Write-LogInfo "Creating desktop shortcut at $shortcutPath..."

try {
    $wshShell = New-Object -ComObject WScript.Shell

    # Remove existing shortcut if present (idempotent).
    if (Test-Path $shortcutPath) {
        Remove-Item $shortcutPath -Force
        Write-LogInfo "Removed existing shortcut."
    }

    $shortcut = $wshShell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = $batchFile
    $shortcut.WorkingDirectory = $picryptDir
    $shortcut.Description = "Picrypt Panic Lock - Emergency lock all devices"
    $shortcut.WindowStyle = 7  # Minimized

    # Set the hotkey: Ctrl+Shift+L
    # WScript.Shell hotkey format: "Ctrl+Shift+L"
    $shortcut.Hotkey = "Ctrl+Shift+L"

    # Try to set an icon. Use a lock icon from shell32.dll if available.
    $shortcut.IconLocation = "%SystemRoot%\System32\shell32.dll,47"

    $shortcut.Save()
    Write-LogOk "Desktop shortcut created with hotkey Ctrl+Shift+L."
} catch {
    Write-LogError "Failed to create desktop shortcut: $_"
    throw
} finally {
    if ($null -ne $wshShell) {
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($wshShell) | Out-Null
    }
}

# --------------------------------------------------------------------------- #
# 4. Also create a shortcut in the Start Menu (for discoverability)
# --------------------------------------------------------------------------- #

$startMenuDir = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Picrypt"
$startMenuShortcut = "$startMenuDir\Picrypt Panic Lock.lnk"

Write-LogInfo "Creating Start Menu shortcut..."

try {
    if (-not (Test-Path $startMenuDir)) {
        New-Item -ItemType Directory -Path $startMenuDir -Force | Out-Null
    }

    $wshShell = New-Object -ComObject WScript.Shell

    if (Test-Path $startMenuShortcut) {
        Remove-Item $startMenuShortcut -Force
    }

    $smShortcut = $wshShell.CreateShortcut($startMenuShortcut)
    $smShortcut.TargetPath = $batchFile
    $smShortcut.WorkingDirectory = $picryptDir
    $smShortcut.Description = "Picrypt Panic Lock - Emergency lock all devices"
    $smShortcut.WindowStyle = 7
    $smShortcut.IconLocation = "%SystemRoot%\System32\shell32.dll,47"
    # No hotkey on the Start Menu shortcut to avoid conflicts.
    $smShortcut.Save()
    Write-LogOk "Start Menu shortcut created: $startMenuShortcut"
} catch {
    Write-LogWarn "Could not create Start Menu shortcut: $_"
} finally {
    if ($null -ne $wshShell) {
        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($wshShell) | Out-Null
    }
}

# --------------------------------------------------------------------------- #
# 5. Windows hotkey caveats
# --------------------------------------------------------------------------- #

Write-Host ""
Write-LogInfo "=== Important Notes ==="
Write-Host ""
Write-Host "Windows .lnk hotkeys have limitations:"
Write-Host "  - The shortcut MUST remain on the Desktop (or Start Menu) for the hotkey to work."
Write-Host "  - Explorer.exe must be running (it processes .lnk hotkeys)."
Write-Host "  - There can be a 1-3 second delay the first time the hotkey is pressed."
Write-Host "  - If the hotkey conflicts with another application, it may not work."
Write-Host ""
Write-Host "For faster/more reliable hotkeys, consider:"
Write-Host "  - AutoHotkey (https://www.autohotkey.com/): ^+l::Run, $batchFile"
Write-Host "  - PowerToys Run (map a keyword to the batch file)"
Write-Host ""

# --------------------------------------------------------------------------- #
# Summary
# --------------------------------------------------------------------------- #

Write-Host ""
Write-LogInfo "=== Windows Hotkey Setup Summary ==="
Write-LogInfo "  Batch wrapper:      $batchFile"
Write-LogInfo "  Desktop shortcut:   $shortcutPath"
Write-LogInfo "  Start Menu:         $startMenuShortcut"
Write-LogInfo "  Hotkey:             Ctrl+Shift+L"
if ($picryptFound) {
    Write-LogInfo "  Binary:             $picryptBin"
} else {
    Write-LogInfo "  Binary:             picrypt (not found; will rely on PATH at runtime)"
}
Write-Host ""
Write-LogInfo "To test: press Ctrl+Shift+L or double-click the Desktop shortcut."
Write-LogInfo "To remove:"
Write-LogInfo "  Remove-Item '$shortcutPath'"
Write-LogInfo "  Remove-Item '$startMenuShortcut'"
Write-LogInfo "  Remove-Item '$batchFile'"
